config/routes.rb
Nutritious::Application.routes.draw do

  root 'meals#index'
  resources :meals
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/models/meal.rb
class Meal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
	def index
		@meals = Meal.all
	end

	def new
		@meals = Meal.new
	end

	def create
		Meal.create(meal_params)
		redirect_to root_path
	end

	private

	def meal_params
		params.require(:meal).permit(:name, :ingredients, :instructions)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nutritious</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meals/index.html.erb
<h1>Welcome To My Amazing Web Application! Stay Tuned And Soon This Will Be Amazing!</h1>

<p> The idea of this web app is simple: it will contain a huge selection of healthy meals that people can load and then get information on how to make them, what ingredients are needed, etc. It may include a contribute feature so people can add their own meal ideas. It may also need a feature that allows future admins to approve meal ideas so people don't upload silly things!</p>

<% @meals.each do |meal| %>
	<div>
		<h1> <%= meal.name %> </h1> <br />
		<i> <%= meal.ingredients %> </i><br/>
		<p> <%= meal.instructions %> </p>
	</div>
<% end %>



<%= link_to 'Add Your Meal Idea', new_meal_path %>

app/views/meals/new.html.erb
<h1>Please Enter Your Healthy Meal Details Here!</h1>

<%= simple_form_for @meals do |f| %>
  <%= f.input :name %>
  <%= f.input :ingredients %>
  <%= f.input :instructions %>
  <%= f.submit 'Create' %>
<% end %>